spring.application.name=backend
spring.config.import=optional:file:.env[.properties]
server.port=8080

spring.datasource.url=jdbc:postgresql://localhost:5432/restaurant_db
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.open-in-view=false

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=${MAIL_USERNAME}
spring.mail.password=${MAIL_PASSWORD}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

security.auth.max-failed-attempts=5
security.auth.lock-time-minutes=15

security.jwt.secret-key=${JWT_SECRET_KEY}
security.jwt.expiration-time=${JWT_EXPIRATION}
security.jwt.refresh-expiration-time=${JWT_REFRESH_EXPIRATION}
security.jwt.audience=admin-panel

app.setup.seed-database=${SEED_DATABASE}
app.setup.admin.email=${ADMIN_EMAIL}
app.setup.admin.password=${ADMIN_PASSWORD}

app.cors.allowed-origins=${CORS_ALLOWED_ORIGINS}

logging.level.org.springframework.web=INFO
logging.level.org.hibernate.SQL=DEBUG
logging.level.pl.app.backend=DEBUG

spring.output.ansi.enabled=ALWAYS